namespace Wizard.Core;

/// <summary>
/// Instructions for an AI coding assistant (plan 12.6): the AI tab and download, and the zip's
/// CLAUDE.md and .github/copilot-instructions.md. Project facts come first, then Verify's context-file
/// template from docs/ai-usage.md. The template's inline snapshot sections are dropped: inline
/// snapshots are still beta and the wizard does not enable them.
/// </summary>
public static class AiContentGenerator
{
    public static string Build(Plan plan)
    {
        var builder = new MarkdownBuilder();
        builder.Heading(1, $"{plan.SolutionName}: instructions for AI coding assistants");
        builder.Paragraph($"Generated by the [Verify wizard]({plan.WizardUrl}). This project was set up with Verify snapshot testing; the facts below describe that setup.");

        builder.Heading(2, "Project facts");
        builder.Bullets(
        [
            $"Solution: `{plan.SolutionName}.slnx`. Code under test is in `src/{plan.LibraryProject}`, tests in `src/{plan.TestProject}`.",
            $"Test framework: {plan.Framework.Framework.Name()}{LanguageNote(plan)}.",
            $"Run the tests from the solution directory with `{Plan.TestCommand}`.{RunnerNote(plan)}",
            $"Target framework `{WizardDefaults.TargetFramework}`, SDK pinned by `global.json` ({WizardDefaults.SdkVersion}).",
            "Packages use Central Package Management: add or change versions in `Directory.Packages.props`, and reference packages without a version.",
            $"Verify packages: {string.Join(", ", plan.TestPackages.Where(_ => _.StartsWith("Verify", StringComparison.Ordinal)).Select(_ => $"{_} {plan.Version(_)}"))}.",
            InitializationFact(plan),
            $"The Open Source Maintenance Fee declaration is in `Directory.Build.props` ({SponsorRules.Summary(plan.State)}). Do not remove it: without it every build fails with SC021."
        ]);

        builder.Raw(ContentFiles.Raw("context.md"));

        builder.Heading(2, "Environment");
        builder.Bullets(
        [
            "Set `DiffEngine_Disabled=true` when running tests, so no diff tool opens for each failed snapshot. The exception message still carries the file paths and the content.",
            "When asked to change code that has Verify tests, run the tests first: the `.received.*` files show exactly what changed.",
            "A new test fails on its first run because it has no `.verified.*` file yet. Review the `.received.*` file, then accept it by copying it to the `Verified:` path from the exception message."
        ]);
        return builder.ToString();
    }

    /// <summary>The Verify skill file (plan 12.6), for .claude/skills/verify-snapshot-testing/SKILL.md.</summary>
    public static string Skill() =>
        ContentFiles.Raw("skill.md");

    static string LanguageNote(Plan plan)
    {
        if (plan.Framework.IsFSharp)
        {
            return " (tests in F#, code under test in C#)";
        }

        return "";
    }

    static string RunnerNote(Plan plan)
    {
        if (plan.Framework.UsesTestingPlatform)
        {
            return " The test project runs on Microsoft.Testing.Platform (`global.json` sets the runner), so `dotnet run --project` on it also works.";
        }

        return " Fixie runs on VSTest, which is why `global.json` does not select the Microsoft.Testing.Platform runner.";
    }

    static string InitializationFact(Plan plan)
    {
        if (plan.Framework.IsFSharp)
        {
            return "Verify is configured by the lazy `initialize` value in `Tests.fs`; every test forces it before verifying.";
        }

        return "Verify is configured in `ModuleInitializer.cs` in the test project. Explicit plugin `Initialize` calls go before `VerifierSettings.InitializePlugins()`.";
    }
}
