/// <summary>
/// Instructions for an AI coding assistant (plan 12.6): the AI tab and download, and the zip's
/// CLAUDE.md and .github/copilot-instructions.md. Project facts come first, then Verify's context-file
/// template from docs/ai-usage.md. The template's inline snapshot sections are kept only when inline
/// snapshots are enabled (plan 12.8).
/// </summary>
public static class AiContentGenerator
{
    public static string Build(Plan plan)
    {
        if (plan.IsAddition)
        {
            return BuildAddition(plan);
        }

        var builder = new MarkdownBuilder();
        builder.Heading(1, $"{plan.SolutionName}: instructions for AI coding assistants");
        builder.Paragraph($"Generated by the [Verify wizard]({plan.WizardUrl}). This project was set up with Verify snapshot testing; the facts below describe that setup.");

        builder.Heading(2, "Project facts");
        builder.Bullets(
        [
            $"Solution: `{plan.SolutionName}.slnx`. Code under test is in `src/{plan.LibraryProject}`, tests in `src/{plan.TestProject}`.",
            $"Test framework: {plan.Framework.Framework.Name()}{LanguageNote(plan)}.",
            $"Run the tests from the solution directory with `{Plan.TestCommand}`.{RunnerNote(plan)}",
            $"Target framework `{WizardDefaults.TargetFramework}`, SDK pinned by `global.json` ({WizardDefaults.SdkVersion}).",
            "Packages use Central Package Management: add or change versions in `Directory.Packages.props`, and reference packages without a version.",
            $"Verify packages: {string.Join(", ", plan.TestPackages.Where(_ => _.StartsWith("Verify", StringComparison.Ordinal)).Select(_ => $"{_} {plan.Version(_)}"))}.",
            InitializationFact(plan),
            .. InlineFacts(plan),
            $"The Open Source Maintenance Fee declaration is in `Directory.Build.props` ({SponsorRules.Summary(plan.State)}). Do not remove it: without it every build fails with SC021."
        ]);

        AppendPlugins(builder, plan);
        builder.Raw(Context(plan));

        builder.Heading(2, "Environment");
        builder.Bullets(
        [
            "Set `DiffEngine_Disabled=true` when running tests, so no diff tool opens for each failed snapshot. The exception message still carries the file paths and the content.",
            "When asked to change code that has Verify tests, run the tests first: the `.received.*` files show exactly what changed.",
            FirstRunFact(plan)
        ]);
        return builder.ToString();
    }

    static string Context(Plan plan)
    {
        if (plan.Inline)
        {
            return ContentFiles.Raw("context-inline.md");
        }

        return ContentFiles.Raw("context.md");
    }

    static IEnumerable<string> InlineFacts(Plan plan)
    {
        if (!plan.Inline)
        {
            yield break;
        }

        yield return "Inline snapshots are on (`VerifierSettings.Inline()` in the module initializer): a text snapshot is the `.Snapshot(...)` literal in the test source. A verification that cannot be inlined, such as an image, a document or a test whose parameters reach the verified name, uses a `.verified.` file.";
    }

    static string FirstRunFact(Plan plan)
    {
        if (plan.Inline)
        {
            return "A new test fails on its first run because it has no snapshot yet. For an inline snapshot, review the received text and add it to the test as the `.Snapshot(...)` literal at the `Source:` location. For a file snapshot, review the `.received.*` file, then copy it to the `Verified:` path from the exception message.";
        }

        return "A new test fails on its first run because it has no `.verified.*` file yet. Review the `.received.*` file, then accept it by copying it to the `Verified:` path from the exception message.";
    }

    /// <summary>
    /// For the add flows (plan 12.6 §5): an ordered task list for merging the download into a project
    /// that already uses Verify, each step naming the file it comes from, then the same plugin notes.
    /// </summary>
    static string BuildAddition(Plan plan)
    {
        var builder = new MarkdownBuilder();
        builder.Heading(1, "Adding Verify plugins: instructions for AI coding assistants");
        builder.Paragraph($"Generated by the [Verify wizard]({plan.WizardUrl}). The files next to this one are changes to merge into a project that already uses Verify snapshot testing with {plan.Framework.Framework.Name()}. Carry out the steps below in order.");

        var tasks = new List<string>
        {
            $"If the solution uses Central Package Management (a `Directory.Packages.props` with `ManagePackageVersionsCentrally`), merge the `PackageVersion` items from `{AdditionGenerator.PackagesFragment}` into it. Otherwise give each `PackageReference` in the next step the version listed in that file.",
            $"Merge `{AdditionGenerator.ProjectFragment}` into the test project: the `PackageReference` items, and any properties and items it has."
        };

        if (plan.Framework.IsFSharp)
        {
            tasks.Add("Merge `initialize.fragment.fs` into the lazy value the tests force before verifying. Keep the calls in the order given.");
        }
        else
        {
            tasks.Add("Merge `ModuleInitializer.cs` into the test project's existing module initializer. Explicit `Initialize` calls go above `VerifierSettings.InitializePlugins()`, in the order given: a plugin can only be initialized once, so a call with parameters has to come before discovery. Calls after `InitializePlugins()` stay after it. If the project has no module initializer, add the file as it is.");
        }

        foreach (var existing in plan.ExistingChanges.Where(_ => _.Statements.Count > 0))
        {
            tasks.Add($"{existing.Definition.DisplayName} is already in the project. Replace its existing initialization with `{string.Join(" ", existing.Statements.Select(_ => _.Code))}`, or, if the project relies on `InitializePlugins()` to enable it, add that call above `InitializePlugins()`.");
        }

        if (plan.Plugins.Any(_ => _.Samples.Count > 0))
        {
            tasks.Add("Copy `Plugins/` into the test project.");
        }

        if (plan.Plugins.Any(_ => _.Definition.LibraryFiles.Count > 0))
        {
            tasks.Add($"The tests use placeholder types from `{AdditionGenerator.SamplesFolder}/`. Prefer pointing the tests at the project's real types; otherwise copy the placeholders into a project the tests reference.");
        }

        if (AdditionGenerator.Sponsor(plan) != null)
        {
            tasks.Add($"Merge `{AdditionGenerator.SponsorFragment}` into `Directory.Build.props`. A block that is commented out is a decision for the user; do not choose one of its options on their behalf.");
        }

        if (plan.DotnetTools.Count > 0)
        {
            tasks.Add($"Merge `{AdditionGenerator.ToolsFragment}` into `.config/dotnet-tools.json`, then run `dotnet tool restore`.");
        }

        if (plan.Inline)
        {
            tasks.Add("`VerifierSettings.Inline()` moves every existing text snapshot inline. On the next run each of those tests fails as `InlineNew` and its `.verified.` file is listed under `Delete:`. Tell the user before running the tests; once they agree, write each received text into the `.Snapshot(...)` literal at its `Source:` location and delete the listed files.");
        }

        tasks.Add("Build, then run the tests with `DiffEngine_Disabled=true`. The new tests fail on their first run because they have no `.verified.` files yet. Show the user each `.received.` file; accept one only once the user agrees it is right.");

        builder.Heading(2, "Steps");
        builder.Numbered(tasks);

        AppendPlugins(builder, plan);
        builder.Raw(Context(plan));
        return builder.ToString();
    }

    /// <summary>
    /// The plugin cheat sheet (plan 12.6 §6): what each one is enabled by, what it puts in a
    /// snapshot, and the decisions the interaction rules took, as instructions rather than as prose.
    /// </summary>
    static void AppendPlugins(MarkdownBuilder builder, Plan plan)
    {
        if (plan.Plugins.Count == 0)
        {
            return;
        }

        builder.Heading(2, "Verify plugins in this project");
        foreach (var plugin in plan.Plugins)
        {
            var definition = plugin.Definition;
            builder.Heading(3, definition.DisplayName);
            var facts = new List<string>
            {
                definition.Description,
                $"Repository: {definition.RepoUrl}"
            };
            if (plugin.Statements.Count > 0)
            {
                facts.Add($"Enabled in `ModuleInitializer.cs` by `{string.Join(' ', plugin.Statements.Select(_ => _.Code))}`. Do not move that call after `VerifierSettings.InitializePlugins()`.");
            }

            if (plugin.Samples.Count > 0)
            {
                facts.Add($"Samples: `Plugins/{plugin.TestClass}.cs`, using {string.Join(", ", plugin.Samples.Select(_ => $"`{_.Name}`"))}.");
            }

            if (definition.Usings.Count > 0)
            {
                facts.Add($"Needs {string.Join(", ", definition.Usings.Select(_ => $"`using {_};`"))} in the test file, not in global usings: plugins define colliding type names.");
            }

            facts.AddRange(definition.Notes);
            builder.Bullets(facts);
        }

        if (plan.Interactions.Count == 0)
        {
            return;
        }

        builder.Heading(2, "Decisions already taken");
        builder.Paragraph("These follow from the combination of plugins. Changing one of them changes behaviour across the whole test project.");
        builder.Bullets(plan.Interactions.Select(Instruction));
    }

    static string Instruction(InteractionResult interaction)
    {
        var text = $"**{string.Join(", ", interaction.Involved)}**: {interaction.Message}";
        if (interaction.Choice is { } choice &&
            choice.Options.FirstOrDefault(_ => _.Value == interaction.ChosenValue) is { } chosen)
        {
            return $"{text} In force: {chosen.Label}.";
        }

        return text;
    }


    static string LanguageNote(Plan plan)
    {
        if (plan.Framework.IsFSharp)
        {
            return " (tests in F#, code under test in C#)";
        }

        return "";
    }

    static string RunnerNote(Plan plan)
    {
        if (plan.Framework.UsesTestingPlatform)
        {
            return " The test project runs on Microsoft.Testing.Platform (`global.json` sets the runner), so `dotnet run --project` on it also works.";
        }

        return " Fixie runs on VSTest, which is why `global.json` does not select the Microsoft.Testing.Platform runner.";
    }

    static string InitializationFact(Plan plan)
    {
        if (plan.Framework.IsFSharp)
        {
            return "Verify is configured by the lazy `initialize` value in `Tests.fs`; every test forces it before verifying.";
        }

        return "Verify is configured in `ModuleInitializer.cs` in the test project. Explicit plugin `Initialize` calls go before `VerifierSettings.InitializePlugins()`.";
    }
}
