namespace Wizard.Core;

/// <summary>
/// One build definition per build server: build, run the tests, and publish any <c>*.received.*</c>
/// files when they fail, using the steps from Verify's build-server docs (plan 12.2).
/// </summary>
public static class BuildServerFiles
{
    /// <returns>The path and content, or null for <see cref="BuildServer.None"/>.</returns>
    public static (string Path, string Content)? For(Plan plan) =>
        plan.BuildServer switch
        {
            BuildServer.GitHubActions => (".github/workflows/build.yml", GitHubActions(plan)),
            BuildServer.AzureDevOps => ("azure-pipelines.yml", AzureDevOps(plan)),
            BuildServer.AppVeyor => ("appveyor.yml", AppVeyor(plan)),
            _ => null
        };

    static string GitHubActions(Plan plan) =>
        $"""
         # Generated by the Verify wizard: {plan.WizardUrl}
         name: Build

         on:
           push:
           pull_request:

         jobs:
           build:
             runs-on: ubuntu-latest
             steps:
               - uses: actions/checkout@v4

               - name: Setup .NET
                 uses: actions/setup-dotnet@v5
                 with:
                   global-json-file: global.json

               - name: Build
                 run: dotnet build --configuration Release

               - name: Test
                 run: {Plan.TestCommand} --configuration Release --no-build

               # Verify writes a *.received.* file for every snapshot that does not match. Uploading them
               # when the build fails makes the difference visible without re-running locally.
               - name: Upload Test Results
                 if: failure()
                 uses: actions/upload-artifact@v4
                 with:
                   name: verify-test-results
                   path: |
                     **/*.received.*

         """;

    static string AzureDevOps(Plan plan) =>
        $"""
         # Generated by the Verify wizard: {plan.WizardUrl}
         trigger:
           - main

         pool:
           vmImage: ubuntu-latest

         steps:
           - task: UseDotNet@2
             displayName: 'Install the .NET SDK from global.json'
             inputs:
               useGlobalJson: true

           - script: dotnet build --configuration Release
             displayName: 'Build'

           - script: {Plan.TestCommand} --configuration Release --no-build
             displayName: 'Test'

           # Verify writes a *.received.* file for every snapshot that does not match. These steps publish
           # them as a build artifact when the tests fail.
           - task: CmdLine@2
             displayName: 'Set flag to publish Verify *.received.* files when test step fails'
             condition: failed()
             inputs:
               script: 'echo "##vso[task.setvariable variable=publishverify]Yes"'

           - task: CopyFiles@2
             condition: eq(variables['publishverify'], 'Yes')
             displayName: 'Copy Verify *.received.* files to Artifact Staging'
             inputs:
               contents: '**/*.received.*'
               targetFolder: '$(Build.ArtifactStagingDirectory)/Verify'
               cleanTargetFolder: true
               overWrite: true

           - task: PublishBuildArtifacts@1
             displayName: 'Publish Verify *.received.* files as Artifacts'
             name: 'verifypublish'
             condition: eq(variables['publishverify'], 'Yes')
             inputs:
               PathtoPublish: '$(Build.ArtifactStagingDirectory)/Verify'
               ArtifactName: 'Verify'
               publishLocation: 'Container'

         """;

    static string AppVeyor(Plan plan) =>
        $"""
         # Generated by the Verify wizard: {plan.WizardUrl}
         image: Visual Studio 2022
         environment:
           DOTNET_NOLOGO: true
           DOTNET_CLI_TELEMETRY_OPTOUT: true
         # The image may not have the SDK global.json pins, so install it.
         install:
           - pwsh: |
               Invoke-WebRequest "https://dot.net/v1/dotnet-install.ps1" -OutFile "./dotnet-install.ps1"
               ./dotnet-install.ps1 -JSonFile global.json -Architecture x64 -InstallDir 'C:\Program Files\dotnet'
         build_script:
           - dotnet build --configuration Release
         test_script:
           - {Plan.TestCommand} --configuration Release --no-build
         # Verify writes a *.received.* file for every snapshot that does not match. Push them as artifacts
         # when the build fails.
         on_failure:
           - ps: Get-ChildItem *.received.* -recurse | % {"{"} Push-AppveyorArtifact $_.FullName -FileName $_.Name {"}"}

         """;
}
