namespace Wizard.Core;

/// <summary>
/// One build definition per build server: build, run the tests, and publish any <c>*.received.*</c>
/// files when they fail, using the steps from Verify's build-server docs (plan 12.2).
/// </summary>
public static class BuildServerFiles
{
    /// <returns>The path and content, or null for <see cref="BuildServer.None"/>.</returns>
    public static (string Path, string Content)? For(Plan plan) =>
        plan.BuildServer switch
        {
            BuildServer.GitHubActions => (".github/workflows/build.yml", GitHubActions(plan)),
            BuildServer.AzureDevOps => ("azure-pipelines.yml", AzureDevOps(plan)),
            BuildServer.AppVeyor => ("appveyor.yml", AppVeyor(plan)),
            _ => null
        };

    static string GitHubActions(Plan plan)
    {
        var builder = new StringBuilder(
            $"""
             # Generated by the Verify wizard: {plan.WizardUrl}
             name: Build

             on:
               push:
               pull_request:

             jobs:

             """);
        AppendGitHubJob(builder, plan, windows: false);
        if (plan.HasWindowsProject)
        {
            AppendGitHubJob(builder, plan, windows: true);
        }

        return builder.ToString();
    }

    /// <summary>
    /// The Windows-only extensions build only on Windows, so when any is selected the portable job
    /// names the projects it can build and a second job on windows-latest builds the whole solution.
    /// </summary>
    static void AppendGitHubJob(StringBuilder builder, Plan plan, bool windows)
    {
        var name = "build";
        var image = "ubuntu-latest";
        var target = "";
        if (windows)
        {
            name = "windows";
            image = "windows-latest";
        }
        else if (plan.HasWindowsProject)
        {
            target = $" src/{plan.TestProject}";
        }

        builder.Append(
            $"""
               {name}:
                 runs-on: {image}
                 steps:
                   - uses: actions/checkout@v4

                   - name: Setup .NET
                     uses: actions/setup-dotnet@v5
                     with:
                       global-json-file: global.json


             """);

        foreach (var step in ToolSteps(plan, windows))
        {
            builder.Append(step);
            builder.Append('\n');
        }

        builder.Append(
            $"""
                   - name: Build
                     run: dotnet build{target} --configuration Release

                   - name: Test
                     run: {Plan.TestCommand}{target} --configuration Release --no-build
             {Secrets(plan)}
                   # Verify writes a *.received.* file for every snapshot that does not match. Uploading them
                   # when the build fails makes the difference visible without re-running locally.
                   - name: Upload Test Results
                     if: failure()
                     uses: actions/upload-artifact@v4
                     with:
                       name: verify-test-results-{name}
                       path: |
                         **/*.received.*


             """);
    }

    /// <summary>Install steps for the external tools the selected extensions need, where one exists.</summary>
    static IEnumerable<string> ToolSteps(Plan plan, bool windows)
    {
        foreach (var requirement in plan.ExtensionsIn(windows).SelectMany(_ => _.Definition.ExternalRequirements))
        {
            var install = windows ? requirement.WindowsInstall : requirement.LinuxInstall;
            if (install == null)
            {
                continue;
            }

            yield return
                $"""
                       - name: Install {requirement.Name}
                         run: {install}

                 """;
        }
    }

    /// <summary>
    /// Licence keys and api keys are read from the environment, so the test step needs them passed
    /// through from the repository's secrets.
    /// </summary>
    static string Secrets(Plan plan)
    {
        var variables = plan.Extensions
            .SelectMany(_ => _.Definition.ExternalRequirements)
            .Select(_ => _.EnvironmentVariable)
            .OfType<string>()
            .Distinct(StringComparer.Ordinal)
            .Order(StringComparer.Ordinal)
            .ToList();
        if (variables.Count == 0)
        {
            return "";
        }

        var builder = new StringBuilder("        env:\n");
        foreach (var variable in variables)
        {
            builder.Append($"          {variable}: ${{{{ secrets.{variable} }}}}\n");
        }

        return builder.ToString();
    }

    static string AzureDevOps(Plan plan) =>
        $"""
         # Generated by the Verify wizard: {plan.WizardUrl}
         trigger:
           - main

         pool:
           vmImage: ubuntu-latest

         steps:
           - task: UseDotNet@2
             displayName: 'Install the .NET SDK from global.json'
             inputs:
               useGlobalJson: true

           - script: dotnet build --configuration Release
             displayName: 'Build'

           - script: {Plan.TestCommand} --configuration Release --no-build
             displayName: 'Test'

           # Verify writes a *.received.* file for every snapshot that does not match. These steps publish
           # them as a build artifact when the tests fail.
           - task: CmdLine@2
             displayName: 'Set flag to publish Verify *.received.* files when test step fails'
             condition: failed()
             inputs:
               script: 'echo "##vso[task.setvariable variable=publishverify]Yes"'

           - task: CopyFiles@2
             condition: eq(variables['publishverify'], 'Yes')
             displayName: 'Copy Verify *.received.* files to Artifact Staging'
             inputs:
               contents: '**/*.received.*'
               targetFolder: '$(Build.ArtifactStagingDirectory)/Verify'
               cleanTargetFolder: true
               overWrite: true

           - task: PublishBuildArtifacts@1
             displayName: 'Publish Verify *.received.* files as Artifacts'
             name: 'verifypublish'
             condition: eq(variables['publishverify'], 'Yes')
             inputs:
               PathtoPublish: '$(Build.ArtifactStagingDirectory)/Verify'
               ArtifactName: 'Verify'
               publishLocation: 'Container'

         """;

    static string AppVeyor(Plan plan) =>
        $"""
         # Generated by the Verify wizard: {plan.WizardUrl}
         image: Visual Studio 2022
         environment:
           DOTNET_NOLOGO: true
           DOTNET_CLI_TELEMETRY_OPTOUT: true
         # The image may not have the SDK global.json pins, so install it.
         install:
           - pwsh: |
               Invoke-WebRequest "https://dot.net/v1/dotnet-install.ps1" -OutFile "./dotnet-install.ps1"
               ./dotnet-install.ps1 -JSonFile global.json -Architecture x64 -InstallDir 'C:\Program Files\dotnet'
         build_script:
           - dotnet build --configuration Release
         test_script:
           - {Plan.TestCommand} --configuration Release --no-build
         # Verify writes a *.received.* file for every snapshot that does not match. Push them as artifacts
         # when the build fails.
         on_failure:
           - ps: Get-ChildItem *.received.* -recurse | % {"{"} Push-AppveyorArtifact $_.FullName -FileName $_.Name {"}"}

         """;
}
