namespace Wizard.Core;

/// <summary>Source files of the generated solution. Every file starts with a banner linking back to the wizard (plan 12.2).</summary>
public static class CodeFiles
{
    public static string Banner(Plan plan, string commentPrefix = "//") =>
        $"""
         {commentPrefix} Generated by the Verify wizard: {plan.WizardUrl}
         {commentPrefix} Delete whatever is not needed.

         """;

    /// <summary>Verify's TargetLibrary sample (src/TargetLibrary/ClassBeingTested.cs in the Verify repo).</summary>
    public static string ClassBeingTested(Plan plan) =>
        Banner(plan) +
        """
        // Stands in for real code under test. Sample.Test verifies what FindPerson returns.
        public static class ClassBeingTested
        {
            public static Person FindPerson() =>
                new()
                {
                    Id = new("ebced679-45d3-4653-8791-3d969c4a986c"),
                    Title = Title.Mr,
                    GivenNames = "John",
                    FamilyName = "Smith",
                    Spouse = "Jill",
                    Children =
                    [
                        "Sam",
                        "Mary"
                    ],
                    Address = new()
                    {
                        Street = "4 Puddle Lane",
                        Country = "USA"
                    }
                };
        }

        """;

    /// <summary>Verify's src/TargetLibrary/SampleModels.cs.</summary>
    public static string SampleModels(Plan plan) =>
        Banner(plan) +
        """
        // Fields rather than properties, and uninitialized, to keep the sample short.
        #pragma warning disable CS8618

        public class Person
        {
            public string? GivenNames;
            public string FamilyName;
            public string Spouse;
            public Address Address;
            public List<string> Children;
            public Title Title;
            public Guid Id;
            public DateTimeOffset Dob;
        }

        public class Address
        {
            public string Street;
            public string Suburb;
            public string Country;
        }

        public enum Title
        {
            Mr,
            Mrs
        }

        """;

    /// <summary>
    /// The known snapshot of the core sample (Verify's Sample.Test.verified.txt), the only verified
    /// file shipped (plan D6). Title and Dob are default values, which Verify omits; Id is scrubbed.
    /// Verified text files are UTF-8 with a BOM and no trailing newline.
    /// </summary>
    public const string SampleVerified =
        """
        {
          GivenNames: John,
          FamilyName: Smith,
          Spouse: Jill,
          Address: {
            Street: 4 Puddle Lane,
            Country: USA
          },
          Children: [
            Sam,
            Mary
          ],
          Id: Guid_1
        }
        """;

    public static string ModuleInitializer(Plan plan) =>
        Banner(plan) +
        """
        using System.Runtime.CompilerServices;
        using VerifyTests.DiffPlex;

        // Everything here runs once, when the test assembly loads, before any test.
        public static class ModuleInitializer
        {
            [ModuleInitializer]
            public static void Initialize()
            {
                // Verify.DiffPlex: when a text snapshot does not match, the failure message shows an inline
                // diff instead of the whole received and verified text.
                // OutputType.Compact prints only the changed lines, with a line of context either side.
                // Alternatives: OutputType.Full, OutputType.Minimal.
                VerifyDiffPlex.Initialize(OutputType.Compact);

                // Initializes every Verify.* plugin the project references and has not initialized above.
                // Explicit calls come first so their parameters apply: a plugin can only be initialized once.
                VerifierSettings.InitializePlugins();
            }
        }

        """;

    public static string SampleTest(Plan plan)
    {
        var verified = plan.Framework.SampleVerifiedFile;
        var received = verified.Replace(".verified.", ".received.");
        return Banner(plan) +
               $"""
                // Verify serializes what FindPerson returns and compares it with {verified}.
                // On a mismatch the test fails, {received} is written next to it, and a diff tool
                // opens. Accepting the change means the received file replaces the verified one.

                """ +
               plan.Framework.SampleTest + "\n";
    }

    public static string VerifyChecksTest(Plan plan) =>
        Banner(plan) +
        """
        // Checks the solution follows Verify's conventions: .gitignore excludes received files, and
        // .gitattributes and .editorconfig have settings for every verified text extension in use.

        """ +
        plan.Framework.VerifyChecksTest + "\n";

    public static string MsTestAssemblyInfo(Plan plan) =>
        Banner(plan) +
        """
        // Verify.MSTest uses a source generator that only processes test classes that opt in. This opts in
        // every test class in the assembly; test classes must be partial.
        [assembly: UsesVerify]

        """;

    public static string FixieTestProject(Plan plan) =>
        Banner(plan) +
        """
        // Fixie leaves test discovery and execution to the project. Verify needs the target assembly
        // assigned, and each test run wrapped in ExecutionState.Set so it knows which test is verifying.

        """ +
        TestFrameworkInfo.FixieTestProject +
        """


        // Fixie has no parameterised test attribute of its own; the convention above runs a method once
        // per [TestCase(...)], passing the values as its parameters.
        [AttributeUsage(AttributeTargets.Method, AllowMultiple = true)]
        public sealed class TestCase(params object[] parameters) :
            Attribute
        {
            public object[] Parameters { get; } = parameters;
        }

        """;

    /// <summary>The Expecto project: F# has no module initializers, so the tests share a lazy setup.</summary>
    public static string ExpectoTests(Plan plan) =>
        Banner(plan, "//") +
        $$"""
        module Tests

        open System.Reflection
        open Expecto
        open VerifyTests
        open VerifyTests.DiffPlex
        open VerifyExpecto

        // F# has no module initializers, so each test forces this before verifying. It runs once.
        // Verify.DiffPlex: a failed text snapshot shows an inline diff instead of the whole text.
        // InitializePlugins initializes any other Verify.* plugin the project references.
        let initialize =
            lazy (
                VerifyDiffPlex.Initialize(OutputType.Compact)
                VerifierSettings.InitializePlugins())

        // Verify serializes what FindPerson returns and compares it with Tests.findPerson.verified.txt.
        {{plan.Framework.SampleTest}}

        // Checks the solution follows Verify's conventions (.gitignore, .gitattributes, .editorconfig).
        {{plan.Framework.VerifyChecksTest}}

        """;
}
