namespace Wizard.Core;

/// <summary>
/// The guide (plan 12.3): shown on the output step, downloadable, and the readme.md of the zip.
/// Section order follows the old docs/wiz pages (plan Appendix C), then adds what the zip contains.
/// Static texts come from Verify's docs (<see cref="ContentFiles"/>). Headings and prose avoid "you",
/// as Verify's docs do.
/// </summary>
public static class DocsGenerator
{
    public static string Build(Plan plan)
    {
        if (plan.IsAddition)
        {
            return BuildAddition(plan);
        }

        var builder = new MarkdownBuilder();
        AppendIntro(builder, plan);
        AppendPackages(builder, plan);
        AppendTestRunner(builder, plan);
        AppendImplicitUsings(builder);
        AppendConventions(builder, plan);
        AppendSnapshotManagement(builder, plan);
        AppendPlugins(builder, plan);
        AppendInteractions(builder, plan);
        AppendModuleInitializer(builder, plan);
        AppendSample(builder, plan);
        AppendDiffTools(builder, plan);
        AppendBuildServer(builder, plan);
        AppendMaintenanceFee(builder, plan);
        AppendRunning(builder, plan);
        AppendReferences(builder);
        return builder.ToString();
    }

    /// <summary>
    /// The add flows' guide (plan 12.5): the changes to make to a project that already uses Verify, in
    /// the order to make them. Everything about setting Verify up is assumed done.
    /// </summary>
    static string BuildAddition(Plan plan)
    {
        var builder = new MarkdownBuilder();
        builder.Heading(1, "Adding Verify plugins");
        builder.Paragraph($"Generated by the [Verify wizard]({plan.WizardUrl}) (reopen that link to change any answer).");
        builder.Bullets(
        [
            $"Test framework: {plan.Framework.Framework.Name()}",
            $"Adding: {PluginSummary(plan)}",
            $"Already in the project: {ExistingSummary(plan)}",
            $"Maintenance fee: {SponsorRules.Summary(plan.State)}",
            $"Package versions: {plan.VersionsNote}"
        ]);
        builder.Paragraph("The download holds the changes below as files to merge, each named for where it goes. `CLAUDE.md` has the same steps written for an AI assistant to carry out.");

        builder.Heading(2, "1. Add the packages");
        builder.Paragraph($"With Central Package Management, merge `{AdditionGenerator.PackagesFragment}` into `Directory.Packages.props`, and the `PackageReference` items in `{AdditionGenerator.ProjectFragment}` into the test project:");
        builder.Code(AdditionGenerator.Packages(plan).TrimEnd(), "xml");
        builder.Paragraph("Without it, reference each package with its version instead:");
        builder.Code(
            string.Join('\n', plan.AddedPackages.Select(_ => $"<PackageReference Include=\"{_}\" Version=\"{plan.Version(_)}\" />")),
            "xml");
        builder.Paragraph("Or from the command line, in the test project's directory:");
        builder.Code(string.Join('\n', plan.AddedPackages.Select(_ => $"dotnet add package {_}")));

        builder.Heading(2, "2. Update the test project");
        builder.Paragraph($"`{AdditionGenerator.ProjectFragment}` has everything the test project gains:");
        builder.Code(AdditionGenerator.Project(plan).TrimEnd(), "xml");

        builder.Heading(2, "3. Update the module initializer");
        AppendAdditionInitializer(builder, plan);

        builder.Heading(2, "4. Add the tests");
        if (plan.Plugins.Any(_ => _.Samples.Count > 0))
        {
            builder.Paragraph("Copy `Plugins/` into the test project. Each file shows one plugin, with a comment above every test saying what it demonstrates.");
        }

        if (plan.Plugins.Any(_ => _.Definition.LibraryFiles.Count > 0))
        {
            builder.Paragraph($"The tests exercise sample types in `{AdditionGenerator.SamplesFolder}/`: a DbContext, a controller, a message handler. They stand in for the project's own types. Either copy them into a project the tests reference, or point the tests at the real ones.");
        }

        AppendPlugins(builder, plan);
        AppendInteractions(builder, plan);

        if (AdditionGenerator.Sponsor(plan) is { } sponsor)
        {
            builder.Heading(2, "Open Source Maintenance Fee");
            builder.Paragraph($"Merge `{AdditionGenerator.SponsorFragment}` into `Directory.Build.props`:");
            builder.Code(sponsor.TrimEnd(), "xml");
        }

        builder.Heading(2, "Running the tests");
        AppendBeforeRunning(builder, plan);
        AppendFirstRun(builder);
        AppendReferences(builder);
        return builder.ToString();
    }

    static string ExistingSummary(Plan plan)
    {
        var existing = Plugins.All.Where(_ => plan.State.IsExisting(_.Id)).Select(_ => _.Id).ToList();
        if (existing.Count == 0)
        {
            return "none listed";
        }

        return string.Join(", ", existing);
    }

    static void AppendAdditionInitializer(MarkdownBuilder builder, Plan plan)
    {
        if (plan.Framework.IsFSharp)
        {
            builder.Paragraph("F# has no module initializers. Merge `initialize.fragment.fs` into the lazy value the tests force before verifying, keeping the order.");
            return;
        }

        builder.Paragraph("`ModuleInitializer.cs` is a complete initializer for the plugins being added. To merge it into the project's own: explicit `Initialize` calls go above `VerifierSettings.InitializePlugins()`, because a plugin can only be initialized once and a call with parameters has to get in before discovery does. Calls after `InitializePlugins()` stay after it.");
        if (plan.ExistingChanges.Count > 0)
        {
            builder.Paragraph($"It also changes the initialization of {InteractionRules.Join([.. plan.ExistingChanges.Select(_ => _.Id)])}, which the project already has. The comment above each of those calls says what to replace.");
        }

        builder.Code(StripBanner(ModuleInitializerGenerator.Build(plan)), "cs");
    }

    static void AppendIntro(MarkdownBuilder builder, Plan plan)
    {
        builder.Heading(1, $"Getting started with Verify: {plan.SolutionName}");
        builder.Paragraph($"Generated by the [Verify wizard]({plan.WizardUrl}) (reopen that link to change any answer).");
        builder.Bullets(
        [
            $"Operating system: {plan.Os.Name()}",
            $"IDE: {plan.Ide.Name()}",
            $"Package management: {plan.Cli.Name()}",
            $"Test framework: {plan.Framework.Framework.Name()}",
            $"Build server: {plan.BuildServer.Name()}",
            $"Plugins: {PluginSummary(plan)}",
            $"Maintenance fee: {SponsorRules.Summary(plan.State)}",
            $".NET: {WizardDefaults.TargetFramework} (SDK {WizardDefaults.SdkVersion})",
            $"Package versions: {plan.VersionsNote}"
        ]);
        builder.Paragraph("The downloadable solution already contains everything described below: a class library, a test project with a passing sample test, and the settings files. This guide explains each part, so the same setup can be applied to an existing solution.");
    }

    static string PluginSummary(Plan plan)
    {
        if (plan.Plugins.Count == 0)
        {
            return "none";
        }

        return string.Join(", ", plan.Plugins.Select(_ => $"{_.Id} ({_.Depth.ToString().ToLowerInvariant()})"));
    }

    static void AppendPackages(MarkdownBuilder builder, Plan plan)
    {
        builder.Heading(2, "Add NuGet packages");
        builder.Paragraph("Add the following packages to the test project. The solution uses [Central Package Management](https://learn.microsoft.com/en-us/nuget/consume-packages/central-package-management): versions live in `Directory.Packages.props`, and project files reference packages without a version.");
        if (plan.Cli == CliPreference.Cli)
        {
            builder.Code(string.Join('\n', plan.TestPackages.Select(_ => $"dotnet add package {_}")));
            builder.Paragraph("With Central Package Management enabled, `dotnet add package` writes the version to `Directory.Packages.props`.");
            return;
        }

        builder.Paragraph("In `Directory.Packages.props`:");
        builder.Code(
            "<ItemGroup>\n" +
            string.Join('\n', plan.TestPackages.Select(_ => $"  <PackageVersion Include=\"{_}\" Version=\"{plan.Version(_)}\" />")) +
            "\n</ItemGroup>",
            "xml");
        builder.Paragraph("In the test project:");
        builder.Code(
            "<ItemGroup>\n" +
            string.Join('\n', plan.TestPackages.Select(_ => $"  <PackageReference Include=\"{_}\" />")) +
            "\n</ItemGroup>",
            "xml");
    }

    static void AppendTestRunner(MarkdownBuilder builder, Plan plan)
    {
        if (!plan.Framework.UsesTestingPlatform)
        {
            builder.Heading(2, "Test runner");
            builder.Paragraph("Fixie has no [Microsoft.Testing.Platform](https://learn.microsoft.com/en-us/dotnet/core/testing/microsoft-testing-platform-intro) runner, so the test project uses VSTest through `Fixie.TestAdapter` and `Microsoft.NET.Test.Sdk`. For the same reason `global.json` does not switch `dotnet test` to Microsoft.Testing.Platform mode, which would stop it running VSTest projects.");
            return;
        }

        builder.Heading(2, "Microsoft.Testing.Platform");
        builder.Raw(ContentFiles.Include("testing-platform"));
        if (plan.Framework.Properties.Count == 0)
        {
            builder.Paragraph($"{plan.Framework.Framework.Name()} sets up the test project as a Microsoft.Testing.Platform app itself, so no project settings are needed.");
            return;
        }

        builder.Heading(3, "Test project settings");
        builder.Paragraph("Add the following to the test project:");
        builder.Code(MsBuildXml.PropertyGroup(plan.Framework.Properties), "xml");
    }

    static void AppendImplicitUsings(MarkdownBuilder builder)
    {
        builder.Heading(2, "Implicit Usings");
        builder.Raw(ContentFiles.Include("implicit-usings"));
    }

    static void AppendConventions(MarkdownBuilder builder, Plan plan)
    {
        builder.Heading(2, "Conventions");
        builder.Heading(3, "Source Control Includes/Excludes");
        builder.Raw(ContentFiles.Include("include-exclude"));
        builder.Heading(3, "Text file settings");
        builder.Raw(ContentFiles.Include("text-file-settings"));
        builder.Heading(3, "Conventions check");
        builder.Paragraph("Conventions can be checked by calling `VerifyChecks.Run()` in a test. The solution includes this test:");
        builder.Code(plan.Framework.VerifyChecksTest, plan.Framework.CodeLanguage);
    }

    static void AppendSnapshotManagement(MarkdownBuilder builder, Plan plan)
    {
        builder.Heading(2, "Snapshot management");
        builder.Paragraph("When a snapshot does not match, Verify writes a `.received.` file next to the `.verified.` one and opens a diff tool. The following tools help review and accept those changes.");

        if (plan.Os == Os.Windows)
        {
            builder.Heading(3, "DiffEngineTray");
            builder.Paragraph("Install [DiffEngineTray](https://github.com/VerifyTests/DiffEngine/blob/main/docs/tray.md).");
            builder.Paragraph("DiffEngineTray sits in the Windows tray. It monitors pending changes in snapshots, and provides a mechanism for accepting or rejecting those changes.");
            builder.Code("dotnet tool install -g DiffEngineTray");
            builder.Paragraph("This is optional, but recommended. Also consider enabling [Run at startup](https://github.com/VerifyTests/DiffEngine/blob/main/docs/tray.md#run-at-startup).");
        }

        if (plan.Ide.UsesJetBrains())
        {
            if (plan.Ide == Ide.Rider)
            {
                builder.Heading(3, "Rider Plugin");
                builder.Paragraph("Install the [Rider Plugin](https://plugins.jetbrains.com/plugin/17240-verify-support).");
                builder.Paragraph("Provides a mechanism for contextually accepting or rejecting snapshot changes inside the Rider test runner.");
            }
            else
            {
                builder.Heading(3, "ReSharper Plugin");
                builder.Paragraph("Install the [ReSharper Plugin](https://plugins.jetbrains.com/plugin/17241-verify-support).");
                builder.Paragraph("Provides a mechanism for contextually accepting or rejecting snapshot changes inside the ReSharper test runner.");
            }

            builder.Paragraph("This is optional, but recommended.");
            builder.Raw(DemoteHeadings(ContentFiles.Include("rider-resharper-orphaned-process"), 1));
            builder.Paragraph($"The solution already includes this setting, in `{plan.SolutionName}.slnx.DotSettings`.");
            builder.Heading(3, "Treat \"return value of pure method is not used\" as error");
            builder.Raw(ContentFiles.Include("pure"));
            builder.Paragraph("The solution's `.editorconfig` already includes this setting.");
        }

        if (plan.Cli == CliPreference.Cli)
        {
            builder.Heading(3, "Verify.Terminal");
            builder.Paragraph("[Verify.Terminal](https://github.com/VerifyTests/Verify.Terminal) is a dotnet tool for managing snapshots from the command line (`dotnet verify review`, `accept` and `reject`). This is optional.");
            builder.Paragraph("The solution installs it as a local tool in `.config/dotnet-tools.json`, so `dotnet tool restore` makes it available. To install it globally instead:");
            builder.Code("dotnet tool install -g verify.tool");
        }
    }

    /// <summary>One subsection per selected plugin (plan 12.3 §9).</summary>
    static void AppendPlugins(MarkdownBuilder builder, Plan plan)
    {
        if (plan.Plugins.Count == 0)
        {
            return;
        }

        builder.Heading(2, "Plugins");
        builder.Paragraph("Each plugin below teaches Verify about one kind of value: how to serialize it, how to compare two of them, or how to turn it into something readable. They are independent; removing one changes nothing else.");

        foreach (var plugin in plan.Plugins)
        {
            AppendPlugin(builder, plan, plugin);
        }
    }

    static void AppendPlugin(MarkdownBuilder builder, Plan plan, ResolvedPlugin plugin)
    {
        var definition = plugin.Definition;
        builder.Heading(3, definition.DisplayName);
        builder.Paragraph($"{definition.Description} ([repository]({definition.RepoUrl}))");

        var packages = plugin.Packages.Where(_ => _.Kind == PackageKind.PackageReference).ToList();
        if (packages.Count > 0)
        {
            builder.Paragraph($"Package{(packages.Count == 1 ? "" : "s")}: {string.Join(", ", packages.Select(_ => Package(plan, _)))}.");
        }

        if (plugin.Statements.Count > 0)
        {
            builder.Paragraph("Enabled by:");
            builder.Code(string.Join('\n', plugin.Statements.Select(_ => _.Code)), "cs");
        }
        else
        {
            builder.Paragraph("Enabled by `VerifierSettings.InitializePlugins()`, which needs no call of its own.");
        }

        foreach (var requirement in definition.ExternalRequirements)
        {
            builder.Paragraph($"Before running: {requirement.Name} is required. {requirement.Description}");
        }

        if (plugin.Samples.Count > 0)
        {
            var depth = plugin.Depth == Depth.Verbose ? "every documented API" : "the most common usage";
            builder.Paragraph($"`Plugins/{plugin.TestClass}.cs` in the download shows {depth}:");
            foreach (var sample in plugin.Samples)
            {
                builder.Paragraph($"**{sample.Name}** — {string.Join(" ", sample.Comment)}");
                builder.Code(sample.Body, "cs");
            }
        }

        if (definition.Notes.Count > 0)
        {
            builder.Paragraph("Notes:");
            builder.Bullets(definition.Notes);
        }
    }

    static string Package(Plan plan, PackageRequirement package)
    {
        var text = $"`{package.Id}` {plan.Version(package.Id)}";
        if (package.Comment is { } comment)
        {
            return $"{text} ({comment})";
        }

        return text;
    }

    /// <summary>Everything the selection implies that no single plugin does (plan 12.3 §10).</summary>
    static void AppendInteractions(MarkdownBuilder builder, Plan plan)
    {
        if (plan.Interactions.Count == 0)
        {
            return;
        }

        builder.Heading(2, "Interactions between the selected plugins");
        foreach (var interaction in plan.Interactions)
        {
            builder.Heading(3, $"{interaction.Severity}: {string.Join(", ", interaction.Involved)}");
            builder.Paragraph(interaction.Message);
            if (interaction.Choice is { } choice)
            {
                builder.Paragraph($"{choice.Label}: **{Label(choice, interaction.ChosenValue)}**. The alternatives:");
                builder.Bullets(choice.Options.Select(_ => $"**{_.Label}** — {_.Hint}"));
            }

            if (interaction.Notes.Count > 0)
            {
                builder.Bullets(interaction.Notes);
            }
        }
    }

    static string Label(PluginChoice choice, string? value) =>
        choice.Options.FirstOrDefault(_ => _.Value == value)?.Label ?? choice.Options[0].Label;

    static void AppendModuleInitializer(MarkdownBuilder builder, Plan plan)
    {
        builder.Heading(2, "Initialization");
        if (plan.Framework.IsFSharp)
        {
            builder.Paragraph("Verify is configured once, before the first verification. F# has no module initializers, so `Tests.fs` holds a lazy value that each test forces first:");
            builder.Code($"let initialize =\n    lazy (\n{CodeFiles.ExpectoInitialize(plan)})", "fs");
            return;
        }

        builder.Paragraph("Verify is configured once, before any test runs, in a [module initializer](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/attributes/general#moduleinitializer-attribute). The solution's `ModuleInitializer.cs`:");
        builder.Code(StripBanner(ModuleInitializerGenerator.Build(plan)), "cs");
    }

    static void AppendSample(MarkdownBuilder builder, Plan plan)
    {
        builder.Heading(2, "Sample Test");
        builder.Code(plan.Framework.SampleTest, plan.Framework.CodeLanguage);
        builder.Paragraph($"`ClassBeingTested.FindPerson()` lives in the `{plan.LibraryProject}` project. The solution includes the approved snapshot, `{plan.Framework.SampleVerifiedFile}`, so this test passes on the first run:");
        builder.Code(CodeFiles.SampleVerified, "txt");

        if (plan.Framework.Framework == TestFramework.MSTest)
        {
            builder.Heading(3, "Marking tests as 'Using Verify'");
            builder.Raw(ContentFiles.Include("mstest-marker", TestFrameworkInfo.DocSnippets));
            builder.Paragraph("The solution uses the assembly-wide attribute, in `AssemblyInfo.cs`.");
        }

        if (plan.Framework.Framework == TestFramework.Fixie)
        {
            builder.Heading(3, "Fixie convention");
            builder.Raw(ContentFiles.Include("fixie-convention", TestFrameworkInfo.DocSnippets));
            builder.Paragraph("The solution includes this as `TestProject.cs`, along with the `[TestCase]` attribute it uses for parameterised tests. `DefaultDiscovery` only runs classes whose names end with `Tests`, which is why the sample class is `SampleTests`.");
        }

        if (plan.Framework.Framework == TestFramework.Expecto)
        {
            builder.Paragraph("Expecto tests pass their name to `Verifier.Verify`, which becomes the snapshot's file name.");
        }
    }

    static void AppendDiffTools(MarkdownBuilder builder, Plan plan)
    {
        builder.Heading(2, "Diff Tool");
        builder.Paragraph("Verify supports many [Diff Tools](https://github.com/VerifyTests/DiffEngine/blob/main/docs/diff-tool.md#supported-tools) for comparing received to verified. While IDEs are supported, due to their MDI nature, using a different Diff Tool is recommended.");
        builder.Paragraph($"Tools supported by {plan.Os.Name()}:");
        builder.Bullets(DiffToolLinks.For(plan.Os).Select(_ => $"[{_.Name}]({_.Url})"));
    }

    static void AppendBuildServer(MarkdownBuilder builder, Plan plan)
    {
        if (BuildServerFiles.For(plan) is not { } file)
        {
            return;
        }

        builder.Heading(2, $"Getting .received in output on {plan.BuildServer.Name()}");
        var include = plan.BuildServer switch
        {
            BuildServer.GitHubActions => "build-server-githubactions",
            BuildServer.AzureDevOps => "build-server-azuredevops",
            _ => "build-server-appveyor"
        };
        builder.Raw(ContentFiles.Include(include));
        builder.Paragraph($"The solution's `{file.Path}` builds, runs the tests, and includes this step.");
    }

    static void AppendMaintenanceFee(MarkdownBuilder builder, Plan plan)
    {
        builder.Heading(2, "Open Source Maintenance Fee");
        builder.Paragraph($"Verify participates in the [Open Source Maintenance Fee]({SponsorXml.FeeDocs}). Organizations using Verify's NuGet packages in revenue-generating activities, with annual gross revenue of at least US$10,000, sponsor [VerifyTests]({SponsorXml.SponsorsPage}) at the tier matching their size. Individuals, non-revenue open source projects and small organizations are exempt.");
        builder.Paragraph("Every Verify package checks at build time that the build declares its status, with a property in `Directory.Build.props`. The solution's declaration:");
        builder.Code(SponsorXml.Block(plan.State, "", plan.SponsorOwners).TrimEnd(), "xml");
        builder.Paragraph($"Expected build outcome: {SponsorRules.Outcome(plan.State)}");
        builder.Paragraph($"The [SponsorCheck setup wizard for Verify]({SponsorXml.SponsorCheckWizard}) explains every option and diagnostic code.");
    }

    static void AppendRunning(MarkdownBuilder builder, Plan plan)
    {
        builder.Heading(2, "Running the tests");
        builder.Paragraph("From the solution directory:");
        builder.Code(Plan.TestCommand);
        if (plan.Framework.UsesTestingPlatform)
        {
            builder.Paragraph($"The test project is also an executable, so `dotnet run --project src/{plan.TestProject}` runs the tests directly.");
        }

        if (plan.HasWindowsProject)
        {
            builder.Paragraph($"`{plan.WindowsTestProject}` targets `{WizardDefaults.TargetFramework}-windows`, because {InteractionRules.Join([.. plan.WindowsPlugins.Select(_ => _.Id)])} renders with Windows APIs. It is part of the solution, so `dotnet test` builds it on Windows and fails on other operating systems. To build only the portable projects there, name them: `dotnet test src/{plan.TestProject}`.");
        }

        AppendBeforeRunning(builder, plan);
        AppendFirstRun(builder);
    }

    static void AppendBeforeRunning(MarkdownBuilder builder, Plan plan)
    {
        var requirements = plan.Plugins
            .SelectMany(_ => _.Definition.ExternalRequirements)
            .DistinctBy(_ => _.Name)
            .ToList();
        if (requirements.Count > 0)
        {
            builder.Heading(3, "Before running");
            builder.Bullets(
                requirements.Select(
                    _ =>
                    {
                        var text = $"**{_.Name}** — {_.Description}";
                        if (_.EnvironmentVariable is { } variable)
                        {
                            text += $" Read from the environment variable `{variable}`.";
                        }

                        if (_.Url is { } url)
                        {
                            text += $" <{url}>";
                        }

                        return text;
                    }));
        }
    }

    static void AppendFirstRun(MarkdownBuilder builder)
    {
        builder.Paragraph("A new test has no `.verified.` file, so its first run fails and writes a `.received.` file. Review it, then accept it by renaming it to `.verified.`, accepting it in the diff tool, DiffEngineTray or IDE plugin, or running `dotnet verify accept`.");
        builder.Paragraph("Set the environment variable `DiffEngine_Disabled=true` when running tests where a diff tool should not open, such as a build server or an AI assistant's terminal. Verify detects the common build servers itself.");
    }

    static void AppendReferences(MarkdownBuilder builder)
    {
        builder.Heading(2, "Further reading");
        builder.Bullets(
        [
            "[Verify readme](https://github.com/VerifyTests/Verify#readme)",
            "[Serializer settings](https://github.com/VerifyTests/Verify/blob/main/docs/serializer-settings.md)",
            "[Scrubbers](https://github.com/VerifyTests/Verify/blob/main/docs/scrubbers.md)",
            "[File naming](https://github.com/VerifyTests/Verify/blob/main/docs/naming.md)",
            "[Parameterised tests](https://github.com/VerifyTests/Verify/blob/main/docs/parameterised.md)",
            "[Plugins](https://github.com/VerifyTests/Verify/blob/main/docs/plugins.md)",
            "[Using Verify with AI assistants](https://github.com/VerifyTests/Verify/blob/main/docs/ai-usage.md)"
        ]);
    }

    /// <summary>Include files are written for a fixed heading depth; nested under a level-3 heading they move down.</summary>
    static string DemoteHeadings(string markdown, int levels) =>
        Regex.Replace(markdown, "^(#+) ", _ => new string('#', _.Groups[1].Length + levels) + " ", RegexOptions.Multiline);

    static string StripBanner(string code) =>
        string.Join('\n', code.Split('\n').SkipWhile(_ => _.StartsWith("//") || _.Length == 0)).TrimEnd();
}
