<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

  <PropertyGroup>
    <TargetFramework>$(GeneratedTargetFramework)</TargetFramework>
    <PublishTrimmed>true</PublishTrimmed>
    <TrimMode>full</TrimMode>
    <InvariantGlobalization>true</InvariantGlobalization>
    <BlazorEnableTimeZoneSupport>false</BlazorEnableTimeZoneSupport>
    <UseNativeHttpHandler>true</UseNativeHttpHandler>
  </PropertyGroup>

  <ItemGroup>
    <TrimmerRootDescriptor Include="ILLink.Descriptors.xml" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" />
    <PackageReference Include="Markdig" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" PrivateAssets="all" />
    <PackageReference Include="ProjectDefaults" PrivateAssets="all" />
    <ProjectReference Include="..\Wizard.Core\Wizard.Core.csproj" />
  </ItemGroup>

</Project>
